### PR TITLE
Broken item table

### LINKED ISSUE #80: Reported broken/lost items table

### PR DESCRIPTION
**Pull request by BrennyChao**

### CODE REVIEW

File: hackathon_site/dashboard/frontend/src/components/dashboard/ItemTable/ItemTable.js [hunk 1]
```diff
@@ -294,3 +296,103 @@ export const PendingTable = ({ items, status }) => {
         </Container>
     );
 };
+
+export const UnconnectedBrokenTable = ({
+    items,
+    isVisible,
+    toggleVisibility,
+    onClickViewReport,
+    status,
```
Comment (lisa-sa-li) [inline hackathon_site/dashboard/frontend/src/components/dashboard/ItemTable/ItemTable.js]: You don't need to pass in a `status` prop. The Orders Pending table has a status for the state of the order (order is ready, order is still is progress, error with order).

File: hackathon_site/dashboard/frontend/src/components/dashboard/ItemTable/ItemTable.js [hunk 2]
```diff
@@ -294,3 +296,103 @@ export const PendingTable = ({ items, status }) => {
...
+                                            src={row.url}
+                                            alt={row.name}
+                                        />
+                                    </TableCell>
+                                    <TableCell align="left">{row.name}</TableCell>
+                                    <TableCell align="right">{row.qty}</TableCell>
+                                    <TableCell align="right">{row.time}</TableCell>
+                                    <TableCell align="left">{row.condition}</TableCell>
+                                    <TableCell align="left">
+                                        <ChipStatus status={status} />
```
Comment (lisa-sa-li) [inline hackathon_site/dashboard/frontend/src/components/dashboard/ItemTable/ItemTable.js]: set `status="error"` since the we just need the red one to be on display always

File: hackathon_site/dashboard/frontend/src/components/dashboard/ItemTable/ItemTable.js [hunk 3]
```diff
@@ -294,3 +296,103 @@ export const PendingTable = ({ items, status }) => {
...
+    status,
+}) => {
+    return !items.length ? null : (
+        <Container
+            className={styles.tableContainer}
+            maxWidth={false}
+            disableGutters={true}
+        >
+            <div className={styles.title}>
+                <Typography variant="h2" className={styles.titleBroken}>
```
Comment (lisa-sa-li) [inline hackathon_site/dashboard/frontend/src/components/dashboard/ItemTable/ItemTable.js]: You can directly put `color="secondary"` on line 314 and remove the extra class you made

File: hackathon_site/dashboard/frontend/src/components/dashboard/ItemTable/ItemTable.js [hunk 4]
```diff
@@ -294,3 +296,103 @@ export const PendingTable = ({ items, status }) => {
...
+                    Reported broken/lost items
+                </Typography>
+                <Button
+                    onClick={() => {
+                        toggleVisibility();
+                    }}
+                    color="primary"
+                >
+                    {isVisible ? "Hide all" : "Show all"}
```
Comment (lisa-sa-li) [inline hackathon_site/dashboard/frontend/src/components/dashboard/ItemTable/ItemTable.js]: I actually don't want this ability to hide the table for the broken items table. If you broke something, I want it to be all up in your face and take up the screen. Instead of deleted all your work, you can transfer it over to `PendingTable` which currently doesn't have the button but could use it

File: hackathon_site/dashboard/frontend/src/testing/mockData.js [hunk 5]
```diff
@@ -96,6 +96,26 @@ export const itemsPending = [
...
+        id: 9,
+        url: "https://i.imgur.com/kOlrXto.jpg",
+        name: "Raspi",
+        qty: 1,
+        time: "9:30PM XX-XX-2020",
+        condition: "Lost",
+    },
+];
+
+export const brokenStatus = "error";
```
Comment (lisa-sa-li) [inline hackathon_site/dashboard/frontend/src/testing/mockData.js]: Delete this

File: hackathon_site/dashboard/frontend/src/slices/ui/uiSlice.js [hunk 6]
```diff
@@ -6,6 +6,7 @@ export const initialState = {
     dashboard: {
```
Comment (lisa-sa-li) [inline hackathon_site/dashboard/frontend/src/slices/ui/uiSlice.js:6]: Don't forget to test uiSlice.test.js!

**Review by lisa-sa-li — CHANGES_REQUESTED** [review]
Great work! Just some minor things and the slight redesign I made. 

Also for future reference, you can see on the Projects tab that the broken item table is issue #80. Next time name the branch `80-broken-table`

File: hackathon_site/dashboard/frontend/src/components/dashboard/ItemTable/ItemTable.js [hunk 7]
```diff
@@ -242,34 +244,140 @@ export const ReturnedTable = connect(returnedTableMapStateToProps, {
...
+                    disableGutters={true}
+                >
+                    <ChipStatus status={status} />
+                    <Button
+                        onClick={() => {
+                            toggleVisibility();
+                        }}
+                        color="primary"
+                    >
+                        {isVisible ? "hide all" : "Show all"}
```
Comment (lisa-sa-li) [inline hackathon_site/dashboard/frontend/src/components/dashboard/ItemTable/ItemTable.js]: I know it doesn't matter but can you change the H to be capital in hide?

File: hackathon_site/dashboard/frontend/src/components/dashboard/ItemTable/ItemTable.module.scss [hunk 8]
```diff
@@ -22,7 +22,14 @@
 
 .titleChip {
```
Comment (lisa-sa-li) [inline hackathon_site/dashboard/frontend/src/components/dashboard/ItemTable/ItemTable.module.scss]: Edit this so it's nested in the `.title` class above
```
.title {
     .....     
     &Chip {
      }
}
```

File: hackathon_site/dashboard/frontend/src/components/dashboard/ItemTable/ItemTable.js [hunk 9]
```diff
@@ -242,34 +244,140 @@ export const ReturnedTable = connect(returnedTableMapStateToProps, {
...
+
+const PendingTableMapStateToProps = (state) => ({
+    isVisible: isPendingTableVisibleSelector(state),
+});
+
+export const PendingTable = connect(PendingTableMapStateToProps, {
+    toggleVisibility: togglePendingTable,
+})(UnconnectedPendingTable);
+
+export const BrokenTable = ({ items, onClickViewReport }) => {
```
Comment (lisa-sa-li) [inline hackathon_site/dashboard/frontend/src/components/dashboard/ItemTable/ItemTable.js]: In `Dashboard.js` create an alert function that will create an alert saying "This would open the report for item of id __". There's already a similar function `Dashboard.js` called `reportIncident`

**Review by lisa-sa-li — CHANGES_REQUESTED** [review]
Just 3 minor things I didn't catch the first time, otherwise all good

File: hackathon_site/dashboard/frontend/src/components/dashboard/ItemTable/ItemTable.js [hunk 10]
```diff
@@ -242,34 +244,140 @@ export const ReturnedTable = connect(returnedTableMapStateToProps, {
...
+
+const PendingTableMapStateToProps = (state) => ({
+    isVisible: isPendingTableVisibleSelector(state),
+});
+
+export const PendingTable = connect(PendingTableMapStateToProps, {
+    toggleVisibility: togglePendingTable,
+})(UnconnectedPendingTable);
+
+export const BrokenTable = ({ items, onClickViewReport, openReportAlert }) => {
```
Comment (lisa-sa-li) [inline hackathon_site/dashboard/frontend/src/components/dashboard/ItemTable/ItemTable.js]: You called the prop `openBrokenTable` instead of `openReportAlert` on Dashboard.js, that's why the alert wasn't working. Also remove the prop `onClickViewReport` cause it's not being used.

File: hackathon_site/dashboard/frontend/src/components/dashboard/ItemTable/ItemTable.js [hunk 11]
```diff
@@ -283,9 +391,21 @@ export const PendingTable = ({ items, status }) => {
...
+                                <TableCell align="right">{row.qty}</TableCell>
+                                <TableCell align="right">{row.time}</TableCell>
+                                <TableCell align="left">{row.condition}</TableCell>
+                                <TableCell align="right">
+                                    <Button
+                                        color="primary"
+                                        size="small"
+                                        onClick={() => {
+                                            openReportAlert(row.id);
+                                            onClickViewReport;
```
Comment (lisa-sa-li) [inline hackathon_site/dashboard/frontend/src/components/dashboard/ItemTable/ItemTable.js]: Delete `onClickViewReport` here too

**Review by lisa-sa-li — APPROVED** [review]
